### ISSUE TITLE
Pagina componenti aggiuntivi

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/mozillaitalia.github.io#10]
Tipo di Issue:

* [x] Modifica Testo sul sito
* [ ] Aggiunta sezione
* [ ] Segnalazione Problemi

Sezione del sito su cui si richiede l'azione:

## Elementi Sito:

* [ ] [Header Sito](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/header.md)
* [ ] [Footer Sito](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/footer.md)
* [ ] [Menu Sito](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/menu.md)

## Pagine Sito:

* [ ] [Home]()
* [ ] [Pagina Download](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/download.md)
* [ ] [Pagina Firefox](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/firefox.md)
* [ ] [Pagina Thunderbird](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/thunderbird.md)
* [ ] [Pagina Lightning](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/lightning.md)
* [ ] [Pagina SeaMonkey](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/seamonkey.md)
* [x] [Pagina Componenti Aggiuntivi](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/componentiaggiuntivi.md)
* [ ] [Finestra Collabora con noi](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/finestracollabora.md)
* [ ] [Pagina Collabora con noi]()
* [ ] [Descrizione Comunità](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/descrizione.md)

**Comment by Mte90** [comment]
Nella sezione:

```Aspetto: modificano l’aspetto dei programmi. Esistono due tipi di componenti aggiuntivi dedicati all’aspetto di Firefox: i temi, che abbelliscono la barra dei menu e l’area delle schede modificandola con un’immagine visualizzata in secondo piano e i temi completi, che modificano l’aspetto dei pulsanti e dei menu.```

Oramai i temi sono solo immagini delle testate e non cambiano più il menu e l'aspetto dei pulsanti.

```Plugin: consentono ai programmi di effettuare operazioni specifiche (come visualizzare immagini speciali o riprodurre contenuto multimediale)```

I plugin non esistono più dalla 52 :-D

**Comment by edovio** [comment]
Ciao @Mte90 vuoi proporre tu una modifica a questa sezione?

**Comment by Mte90** [comment]
Prima di fare la modifica volevo se altri avevano idee invece di fare 1000 pull request.

**Comment by edovio** [comment]
@Mte90 puoi tranquillamente postare le proposte qui, come abbiamo fatto negli altri Issues, senza necessariamente fare mille pull request! :)

**Comment by Sav22999** [comment]
Dal momento che @Mte90 non ha fatto proposte provo a farla io:

Io modificherei completamente tutti i contenuti. Propongo il testo:

### Componenti aggiuntivi
I componenti aggiuntivi permettono di personalizzare, secondo le proprie esigenze e secondo i propri gusti i software. Si possono dividere in tre grandi sezioni:
- Estensioni: permettono di aggiungere funzionalità che inizialmente non sono presenti;
- Temi: permettono di personalizzare l'interfaccia grafica dei software modificando l'aspetto
- Plugin: permettevano di effettuare delle azioni particolari (non sono più supportati dalla versione 52)
### Estensioni
Le estensioni sono piccoli componenti in grado di aggiungere nuove funzionalità ai programmi Mozilla o modificare quelle esistenti.

Vi sono estensioni di ogni tipo, dalle più semplici (come ad esempio Clear Cache Button, che permette di aggiungere un semplice pulsante per cancellare il contenuto della cache) alle più complesse, come ad esempio uBlock Origin che permette di bloccare gli annunci pubblicitari o gli elementi traccianti su qualunque sito web, Facebook Container che permette di isolare totalmente ciò che si fa su Facebook, Messenger, Whatsapp e Instagram.
Le estensioni permettono di adattare i software Mozilla alle proprie esigenze e, al tempo stesso, di mantenerli agili e scattanti. Le estensioni possono essere scaricate dal sito Mozilla Addons.
Sono una caratteristica importante di Firefox poiché è l'unico web browser che possiede le estensioni anche sul mobile (Android).

### Temi
I temi permettono di personalizzare l'interfaccia grafica dei tuoi software scaricandoli e installandoli direttamente da Mozilla Addons. Se non trovi il tema che fa per te puoi realizzarne uno tutto tuo.
La nuova estensione "Firefox Color" (ancora in Test Pilot) permette facilmente di personalizzare tutti i colori di Firefox.

### Plugin
Dalla versione 52 non sono più supportati ufficialmente.
Leggi qui per maggiori informazioni https://support.mozilla.org/en-US/kb/npapi-plugins?as=u&utm_source=inproduct.
