### ISSUE TITLE
Modifica della descrizione della comunità

### ISSUE THREAD

**Issue by edovio** [MozillaItalia/mozillaitalia.github.io#11]
Tipo di Issue:

* [X] Modifica Testo sul sito
* [ ] Aggiunta sezione
* [ ] Segnalazione Problemi

Sezione del sito su cui si richiede l'azione:

## Elementi Sito:

* [ ] [Header Sito](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/header.md)
* [ ] [Footer Sito](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/footer.md)
* [ ] [Menu Sito](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/menu.md)

## Pagine Sito:

* [ ] [Home]()
* [ ] [Pagina Download](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/download.md)
* [ ] [Pagina Firefox](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/firefox.md)
* [ ] [Pagina Thunderbird](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/thunderbird.md)
* [ ] [Pagina Lightning](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/lightning.md)
* [ ] [Pagina SeaMonkey](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/seamonkey.md)
* [ ] [Pagina Componenti Aggiuntivi](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/componentiaggiuntivi.md)
* [ ] [Finestra Collabora con noi](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/finestracollabora.md)
* [ ] [Pagina Come iniziare](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/comeiniziare.md)
* [X] [Descrizione Comunità](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/descrizione.md)
* [ ] [Pagina Dizionari](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/dizionari.md)
* [ ] [Pagina Localizzare le estensioni](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/localizzareleestenzioni.md)
* [ ] [Pagina Manifesto](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/manifesto.md)
* [ ] [Pagina Motori di Ricerca](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/motoridiricerca.md)
* [ ] [Pagina Stile di traduzione](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/regolegeneralilocalizzazione.md)
* [ ] [Pagina SUMO](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/sumo.md)
* [ ] [Pagina Supporto sul forum](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/supportoForum.md)

**Comment by edovio** [comment]
Attualmente il testo di descrizione della comunità dice:

     Siamo un gruppo di volontari che si dedica alla traduzione italiana, al supporto e 
     alla promozione dei prodotti della Mozilla Foundation e derivati.
     In questo sito è raccolto il nostro lavoro: software, traduzioni, articoli e guide.
     Vi raccomandiamo di consultare i nostri forum, per chiedere informazioni o 
     segnalare problemi su tutto ciò che pubblichiamo e, ovviamente, anche per offrire aiuto.

Io propongo di modificarlo con:

     Siamo la comunità Italiana dei volontari della fondazione Mozilla.
     All'interno della nostra comunità ci dedichiamo attivamente alla promozione
     della missione, alla traduzione in lingua Italiana e al supporto di prodotti e siti
     informativi della Fondazione.
     In questo sito è raccolto il nostro lavoro: software, traduzioni, articoli e guide e tutte
     le informazioni per poter partecipare attivamente e unirsi a noi in tutte le attività che 
     svolgiamo.
     Vi raccomandiamo di consultare i nostri forum, per chiedere informazioni o 
     segnalare problemi su tutto ciò che pubblichiamo e, ovviamente, anche per offrire aiuto.

**Comment by kitsunenosaraT** [comment]
Ciao! Parto dalla tua descrizione per proporre piccole modifiche. Ditemi cosa ne pensate.

 Siamo la comunità italiana dei volontari della fondazione Mozilla.
 Ci dedichiamo attivamente alla promozione della missione della Fondazione, alla traduzione in lingua italiana e al supporto dei suoi prodotti, siti informativi ed eventi.
 In questo sito è raccolto il nostro lavoro: software, traduzioni, articoli, guide e tutte
 le informazioni necessarie per entrare a far parte della comunità e partecipare a tutte le attività che svolgiamo.
Invitiamo gli utenti a consultare il forum di Mozilla Italia per chiedere informazioni o segnalare problemi su qualsiasi progetto gestito dalla comunità, ma anche per partecipare alle nostre attività o, semplicemente, offrire un consiglio agli altri utenti in difficoltà.

**Comment by edovio** [comment]
Per me va bene! :)
