### ISSUE TITLE
Aggiungere sezione specifica sulle comunità Locali

### ISSUE THREAD

**Issue by edovio** [MozillaItalia/mozillaitalia.github.io#12]
Tipo di Issue:

* [ ] Modifica Testo sul sito
* [X] Aggiunta sezione
* [ ] Segnalazione Problemi

Sezione del sito su cui si richiede l'azione:

## Elementi Sito:

* [ ] [Header Sito](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/header.md)
* [ ] [Footer Sito](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/footer.md)
* [ ] [Menu Sito](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/menu.md)

## Pagine Sito:

* [ ] [Home]()
* [ ] [Pagina Download](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/download.md)
* [ ] [Pagina Firefox](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/firefox.md)
* [ ] [Pagina Thunderbird](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/thunderbird.md)
* [ ] [Pagina Lightning](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/lightning.md)
* [ ] [Pagina SeaMonkey](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/seamonkey.md)
* [ ] [Pagina Componenti Aggiuntivi](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/componentiaggiuntivi.md)
* [ ] [Finestra Collabora con noi](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/finestracollabora.md)
* [ ] [Pagina Come iniziare](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/comeiniziare.md)
* [ ] [Descrizione Comunità](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/descrizione.md)
* [ ] [Pagina Dizionari](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/dizionari.md)
* [ ] [Pagina Localizzare le estensioni](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/localizzareleestenzioni.md)
* [ ] [Pagina Manifesto](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/manifesto.md)
* [ ] [Pagina Motori di Ricerca](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/motoridiricerca.md)
* [ ] [Pagina Stile di traduzione](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/regolegeneralilocalizzazione.md)
* [ ] [Pagina SUMO](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/sumo.md)
* [ ] [Pagina Supporto sul forum](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/supportoForum.md)

**Comment by edovio** [comment]
Al fine di poter portare avanti quando comunicato durante le call comunitarie precedenti, proporrei di aggiungere una sezione specifica per le comunità locali cittadine.

**Comment by edovio** [comment]
Sotto questo aspetto stavamo valutando un Layout semplice da implementare solo dopo aver creato un documento specifico sulle comunità locali e del materiale minimo di formazione

**Comment by Sav22999** [comment]
Non ho capito bene cosa siano queste "comunità cittadine", potreste spiegare meglio?
