### ISSUE TITLE
Richiesta modifica contenuti - Pagina Come iniziare

### ISSUE THREAD

**Issue by edovio** [MozillaItalia/mozillaitalia.github.io#13]
Tipo di Issue:

* [X] Modifica Testo sul sito
* [ ] Aggiunta sezione
* [ ] Segnalazione Problemi

Sezione del sito su cui si richiede l'azione:

## Elementi Sito:

* [ ] [Header Sito](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/header.md)
* [ ] [Footer Sito](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/footer.md)
* [ ] [Menu Sito](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/menu.md)

## Pagine Sito:

* [ ] [Home]()
* [ ] [Pagina Download](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/download.md)
* [ ] [Pagina Firefox](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/firefox.md)
* [ ] [Pagina Thunderbird](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/thunderbird.md)
* [ ] [Pagina Lightning](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/lightning.md)
* [ ] [Pagina SeaMonkey](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/seamonkey.md)
* [ ] [Pagina Componenti Aggiuntivi](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/componentiaggiuntivi.md)
* [ ] [Finestra Collabora con noi](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/finestracollabora.md)
* [X] [Pagina Come iniziare](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/comeiniziare.md)
* [ ] [Descrizione Comunità](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/descrizione.md)
* [ ] [Pagina Dizionari](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/dizionari.md)
* [ ] [Pagina Localizzare le estensioni](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/localizzareleestenzioni.md)
* [ ] [Pagina Manifesto](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/manifesto.md)
* [ ] [Pagina Motori di Ricerca](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/motoridiricerca.md)
* [ ] [Pagina Stile di traduzione](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/regolegeneralilocalizzazione.md)
* [ ] [Pagina SUMO](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/sumo.md)
* [ ] [Pagina Supporto sul forum](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/supportoForum.md)

**Comment by edovio** [comment]
Credo che sia necessario aggiornare questa sezione eliminando i riferimenti alla associazione e integrando al suo interno le altre attività portate avanti dalla comunità

**Comment by Mte90** [comment]
Cominciamo con un elenco delle attività della comunità così vediamo se basta una lista o ci servono delle spiegazioni per ogni tipologia.

**Comment by kitsunenosaraT** [comment]
Ci vorrebbe una maggiore distinzione tra Mozilla Foundation e i volontari di Mozilla Italia, per chiarire che non siamo stipendiati/riconosciuti legalmente dalla Fondazione. Magari fare due header, es.

> # Chi siamo
> ## Mozilla Foundation
>bla bla bla
> ## Mozilla Italia

La parte della localizzazione andrebbe rivista:
- non si fa cenno alla localizzazione dei progetti web
- i ruoli traduttore / QA sono piuttosto confusi
-l'attività di localizzazione dei progetti web non si svolge più sul forum, ora ci siamo spostati su GitHub.

Che ne dite se ognuno si occupa della sua mini-sezione in questa pagina?

**Comment by edovio** [comment]
Si sono d'accordo! Chi se ne vuole occupare?

**Comment by kitsunenosaraT** [comment]
Io ho una proposta, cioè che ognuno scriva la parte relativa alle attività che gli competono.
Per esempio, io potrei fare gli aggiustamenti riguardo alla parte delle attività di localizzazione, @edovio potrebbe scrivere il paragrafo sui Club (o quel che ha preso il loro posto), @Mte90 le varie attività per sviluppatori ecc.

**Comment by edovio** [comment]
Si va benissimo, in realtà questa parte è strettamente connessa con le eventuali comunità locali, visto che nascono per prendere il posto dei club.

**Comment by Mte90** [comment]
Per sviluppatori posso pensare ad un testo ma non è per niente semplice perché non abbiamo una struttura di supporto per loro italiana se non al fatto che devono puntare a quella internazionale.
Mozilla a così tanti progetti che è impossibile che tutti conoscano tutto, al limite possiamo fare una spiegazione sul fatto che il team è introduttivo e aiuta a capire quali sono le meccaniche più come contribuire ad un progetto specifico.
Consideriamo che il team dev al momento non ha struttura ne ha fatto qualcosa, dare in questo punto una definizione può essere utile per attivarlo

**Comment by edovio** [comment]
Per gli sviluppatori potrebbe essere qualcosa di interessante se si pensasse di creare delle attività o dei format di hackaton pronti all'uso per le comunità locali. In questo modo possiamo provare ad avere ulteriori leve di interesse in generale senza avere roba troppo grossa da mantenere.

**Comment by Mte90** [comment]
Meglio parlarne in call mensile sul tema dev perché è molto ampio :-D

Per il momento non considerate la questione dev così non ci facciamo bloccare.

**Comment by Sav22999** [comment]
Ragazzi, noto che c'è già un issue (questo) aperto per quanto riguarda l'aggiornamento dei contenuti della pagina "Come iniziare".

Per il IHC abbiamo realizzato un Vademecum, quindi un volantino che spieghi per bene progetti di Mozilla, Firefox, tecnologie e c'è una sezione apposita dedicata al "Unisciti a noi". Dunque, ci sono 2 varianti di Vademecum "VG" e "VT", versione generale e versione tecnica.
Nella VG viene spiegato che chiunque è ben accetto (trattando la questione più genericamente possibile... dal momento che è indirizzato a un pubblico generale), mentre per la VT vorremmo inserire un QR che indirizzi a questa pagina, dal momento che è indirizzata ai "tecnici", quindi chi dovrebbe capire un po' di più di tecnologia (e un QR non dovrebbe essere un problema! :P ). Ovviamente, però, non può essere non aggiornata. Quindi mi chiedo, si può fare qualcosa entro il 2 agosto?

Me ne posso occupare anche io, poi voi revisionate. Faccio parte sia del gruppo localizzazione sia di quello developer (e anche in quello design, credo, ma penso sia abbastanza inattivo ora).

Aspetto vostre notizie.
