### ISSUE TITLE
Modifica del testo della Finestra Collabora con noi

### ISSUE THREAD

**Issue by edovio** [MozillaItalia/mozillaitalia.github.io#14]
Tipo di Issue:

* [X] Modifica Testo sul sito
* [ ] Aggiunta sezione
* [ ] Segnalazione Problemi

Sezione del sito su cui si richiede l'azione:

## Elementi Sito:

* [ ] [Header Sito](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/header.md)
* [ ] [Footer Sito](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/footer.md)
* [ ] [Menu Sito](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/menu.md)

## Pagine Sito:

* [ ] [Home]()
* [ ] [Pagina Download](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/download.md)
* [ ] [Pagina Firefox](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/firefox.md)
* [ ] [Pagina Thunderbird](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/thunderbird.md)
* [ ] [Pagina Lightning](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/lightning.md)
* [ ] [Pagina SeaMonkey](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/seamonkey.md)
* [ ] [Pagina Componenti Aggiuntivi](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/componentiaggiuntivi.md)
* [x] [Finestra Collabora con noi](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/finestracollabora.md)
* [ ] [Pagina Come iniziare](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/comeiniziare.md)
* [ ] [Descrizione Comunità](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/descrizione.md)
* [ ] [Pagina Dizionari](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/dizionari.md)
* [ ] [Pagina Localizzare le estensioni](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/localizzareleestenzioni.md)
* [ ] [Pagina Manifesto](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/manifesto.md)
* [ ] [Pagina Motori di Ricerca](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/motoridiricerca.md)
* [ ] [Pagina Stile di traduzione](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/regolegeneralilocalizzazione.md)
* [ ] [Pagina SUMO](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/sumo.md)
* [ ] [Pagina Supporto sul forum](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/supportoForum.md)

**Comment by edovio** [comment]
Attualmente la finestra di collabora con noi indica: 

    Entra a far parte della nostra comunità in modo attivo!

    Scopri in che modo puoi collaborare e aiutaci a portare avanti le 
    nostre attività di traduzione e supporto.

Propongo di modificarlo con:

    Entra a far parte della nostra comunità in modo attivo!

    Scopri in che modo puoi unirti a noi e partecipare attivamente alle nostre attività.

**Comment by kitsunenosaraT** [comment]
Per me 👍

**Comment by Mte90** [comment]
Pure per me!

**Comment by edovio** [comment]
Ottimo, attendiamo qualche altro feedback e nel caso modifichiamo il file

**Comment by Sav22999** [comment]
Io proporrei una piccola modifica:

> 
> Entra a far parte della nostra comunità in modo attivo!
> Scopri in che modo puoi unirti a noi e partecipare attivamente alle nostre tante attività e iniziative.
