### ISSUE TITLE
Modifica Contenuti -- Pagina Stile di traduzione

### ISSUE THREAD

**Issue by kitsunenosaraT** [MozillaItalia/mozillaitalia.github.io#15]
Tipo di Issue:

* [x] Modifica Testo sul sito
* [ ] Aggiunta sezione
* [ ] Segnalazione Problemi

Sezione del sito su cui si richiede l'azione:

## Elementi Sito:

* [ ] [Header Sito](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/header.md)
* [ ] [Footer Sito](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/footer.md)
* [ ] [Menu Sito](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/menu.md)

## Pagine Sito:

* [ ] [Home]()
* [ ] [Pagina Download](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/download.md)
* [ ] [Pagina Firefox](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/firefox.md)
* [ ] [Pagina Thunderbird](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/thunderbird.md)
* [ ] [Pagina Lightning](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/lightning.md)
* [ ] [Pagina SeaMonkey](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/seamonkey.md)
* [ ] [Pagina Componenti Aggiuntivi](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/componentiaggiuntivi.md)
* [ ] [Finestra Collabora con noi](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/finestracollabora.md)
* [ ] [Pagina Come iniziare](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/comeiniziare.md)
* [ ] [Descrizione Comunità](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/descrizione.md)
* [ ] [Pagina Dizionari](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/dizionari.md)
* [ ] [Pagina Localizzare le estensioni](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/localizzareleestenzioni.md)
* [ ] [Pagina Manifesto](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/manifesto.md)
* [ ] [Pagina Motori di Ricerca](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/motoridiricerca.md)
* [x] [Pagina Stile di traduzione](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/regolegeneralilocalizzazione.md)
* [ ] [Pagina SUMO](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/sumo.md)
* [ ] [Pagina Supporto sul forum](https://github.com/MozillaItalia/www.mozillaitalia.org/blob/master/supportoForum.md)

**Comment by kitsunenosaraT** [comment]
In questa pagina ci sarebbero diverse cose da aggiornare.
- In primo luogo, farei una divisione più precisa tra la localizzazione dei progetti web e di SUMO, che seguono regole e stili diversi. In particolare ci sono questi due riferimenti da modificare.

>In caso di dubbi su questioni di stile non affrontate in questo articolo, è possibile consultare questa pagina del Wiki di OpenOffice.org che contiene molti link utili per la traduzione della documentazione tecnica.

Invece di rimandare allo Wiki di Open Office, sarebbe più consono indirizzare alla nostra guida.

>Le discussioni sulla localizzazione avvengono nella sezione localizzazioni del forum e nella sezione dedicata

Questa informazione non è più valida per quanto riguarda i progetti web, che vengono discussi e gestiti attraverso GitHub.

- In secondo luogo arricchirei la pagina con ulteriori link che puntano alle varie sezioni del forum/di GitHub (SUMO, Estensioni, Progetti Web) e risorse varie.

**Comment by edovio** [comment]
Si sono d'accordo! :) vuoi lavorarci tu @kitsunenosaraT oppure lo metto come in ricerca di aiuto?

**Comment by kitsunenosaraT** [comment]
Sarei felice di occuparmene io stessa. Me lo assegno?

**Comment by edovio** [comment]
Si si. anzi dato che ci sono te lo assegno direttamente io xD
