### ISSUE TITLE
Set width limit for the galleries

### ISSUE THREAD

**Issue by mone27** [MozillaItalia/mozillaitalia.github.io#20]
I think that the website looks much better if the galleries doesn't take all the screen but there is space on the left. I simply added the two galleries to the container class and obtained this screenshot
![image](https://user-images.githubusercontent.com/17617810/83908717-dd084c00-a767-11ea-8369-0c583be5f709.png)

Let me know if you like this as well

**Comment by Sav22999** [comment]
@mone27 questo è il repo "Mozilla Italia", puoi parlare tranquillamente in italiano
