### ISSUE TITLE
Change background of the other mozilla projects to white

### ISSUE THREAD

**Issue by mone27** [MozillaItalia/mozillaitalia.github.io#21]
I found that having a blue background in the other mozilla project section works quite badly with other logos because they have all different colors. Hence I see 2 options with the current page content:
1) make "gruppi comunitari" in a blue background (but then there would no difference with the social logins"
2) swap "progetti mozilla" e "eventi" swapping also the color (may be the best options also content-wise)

**Comment by Sav22999** [comment]
@mone27 credo che un'altra possibile soluzione sia quella di mettere una nuova sezione (così ci troviamo con i colori, insomma). Direi "Reps italiani" (visto che siamo tanti ora). @Mte90 cosa ne pensi?

**Comment by Mte90** [comment]
io eviterei quella sezione Reps italiani al momento non c'è alcuna utilità specifica nell'averla.

**Comment by Sav22999** [comment]
La possibilità di contattarli in privato (Telegram), stessa cosa della pagina "Referenti di progetto" diciamo
