### ISSUE TITLE
Aggiungere infografica per spiegare cosa fa Mozilla Italia

### ISSUE THREAD

**Issue by mone27** [MozillaItalia/mozillaitalia.github.io#22]
Alla versione attuale io trovo abbastanza difficile capire (rapidamente) cosa fa Mozilla Italia.
Penso che avere un'infografica (magari un SVG interattivo) può aiutare molto.
Io avevo in mente qualcosa con una struttura del genere
![image](https://user-images.githubusercontent.com/17617810/83918369-e352f400-a778-11ea-8e07-72923228bad7.png)
Bisogna capire che punti vogliamo mettere e poi possiamo pensare a fare un design carino.

Poi anche il pulsante diventa volontario secondo deve portare a qualcosa di più interessante di una lista di link a gruppi telegram che non si capisce bene cosa fanno, penso a avere due righe di spiegazione

Queste sono alcune delle mie idee ma in generale penso che dobbiamo pensare di più a cosa può essere utile per chi visita il sito web

**Comment by dag7dev** [comment]
Ok, secondo me se lo aggiorniamo possiamo usare direttamente il vademecum generale, senza andarci a complicare la vita

**Comment by Sav22999** [comment]
Chiudo questo issue, in quanto è presente una spiegazione chiara nelle "FAQ" https://www.mozillaitalia.org/faq/
