### ISSUE TITLE
Definire obiettivi del sito web di Mozilla Italia

### ISSUE THREAD

**Issue by mone27** [MozillaItalia/mozillaitalia.github.io#23]
Forse questa issue è po' inutile ma penso che chiarire in generale lo scopo del sito ci può aiutare a svilupparlo e mantenerlo.

Per me le cose principali sono:
- far capire a chi non ci conosce cosa siamo e se può interessargli approfondire di più
- invogliare nuovi volontari a unirsi
- permettere a chi ha bisogno di aiuto di trovare il forum di supporto

Per il resto credo che tutte le cose della comunità avvengono su telegram/github/ community portal/discourse anche perchè questo sito verrà aggiornato abbastanza di rado.

**Comment by Sav22999** [comment]
@mone27 Corretto. Il sito sarà statico quanto più possibile.
Ho scritto un README, fammi sapere se è di tuo gradimento o se devo eventualmente aggiungere altri punti.

**Comment by Sav22999** [comment]
Non ho ricevuto risposta, ritengo questo issue chiuso per inattività
