### ISSUE TITLE
Pagina dedicata per "Localizzazione" (presentazione con i link alle varie risorse e gruppi)

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/mozillaitalia.github.io#24]

**Comment by xplosionmind** [comment]
Buongiorno a tutti. Forse sarebbe giusto, prima di completare e pubblicare la pagina, discutere insieme dei contenuti nella riunione comunitaria. Io chiederei, per cominciare, a @danielebarell se volesse aiutarmi indicandomi dei link utili e delle risorse che posso sfruttare per creare la pagina, dato che è molto attivo per la traduzione, in questo momento. Intanto, sto mettendo su la struttura della pagina.

**Comment by Sav22999** [comment]
@xplosionmind un momemento. La pagina **non** deve andare a sostituire l'attuale documentazione, che è ben fatta e completa, piuttosto deve dare delle indicazioni e informazioni rapide a chi volesse entrare nel gruppo

**Comment by Sav22999** [comment]
Ho pubblicato, nel gruppo Design Team (tempo fa) dei mockup di come io avevo pensato questa pagina. Dai un'occhiata, se ti va

**Comment by Sav22999** [comment]
La draft cartacea era questa (chiedo venia per il disordine):
![image](https://user-images.githubusercontent.com/32335378/99338381-5e6e1980-2884-11eb-943f-99ec072fbfaa.png)
