### ISSUE TITLE
Creare pagina "Contatti"

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/mozillaitalia.github.io#33]
Dovrebbe contenere le informazioni per poter contattare Mozilla Italia, ovvero il Forum, Mozilla Discourse, MozItaBot (Telegram), Twitter, Facebook e, magari, chi sono i Rep in Italia (suddividendoli per territorio "Nord Est", "Nord Ovest", "Centro Nord", "Centro Sud", "Sud", "Isole") con il link al profilo su Mozilla People (ed eventuale link al sito web personale?)

**Comment by Mte90** [comment]
Avere i link ai riferimenti social è indispensabile quindi va bene, per i rep serve un incipit che spiega cosa sono

**Comment by Sav22999** [comment]
@Mte90 Sì, esatto

**Comment by xplosionmind** [comment]
> per i rep serve un incipit che spiega cosa sono

Va bene se traduco [questa spiegazione](https://community.mozilla.org/en/groups/mozilla-reps/)?

**Comment by xplosionmind** [comment]
> chi sono i Rep in Italia (suddividendoli per territorio "Nord Est", "Nord Ovest", "Centro Nord", "Centro Sud", "Sud", "Isole") con il link al profilo su Mozilla People (ed eventuale link al sito web personale?)

è sufficiente mettere una lista `<ul>` oppure sarebbe meglio dedicare più spazio, con delle immagini profilo o qualcosa del genere?

**Comment by Sav22999** [comment]
@xplosionmind per fare qualcosa di più coerente con la Home (per "continuità") potresti creare una box tipo quella presente in Home, al posto delle icone metti le immagini ;)

**Comment by Sav22999** [comment]
Per la descrizione penso vada bene se traduci quella. Tanto, come dico sempre, i contenuti devono essere sempre revisionati (nella fase successiva), quindi tranquilli :)

**Comment by xplosionmind** [comment]
Ottimo! C'è un API GitHub che posso usare per prendere le immagini profilo semplicemente selezionando gli username o posso farlo manualmente?

**Comment by Sav22999** [comment]
<s>GitHub, che io sappia, utilizza Gravatar. Quindi è sufficiente che tu abbia il link a Gravatar</s>

E invece no, mi correggo. Non utilizza Gravatar. In ogni caso, sì, ci sono delle API di GitHub: `https://avatars2.githubusercontent.com/u/[USERID]?s=500`
