### ISSUE TITLE
Utilizzare Jekyll

### ISSUE THREAD

**Issue by xplosionmind** [MozillaItalia/mozillaitalia.github.io#35]
Per quanto mi riguarda, avrei molta più dimestichezza a sviluppare il sito, inoltre riterrei potrebbe avere diversi vantaggi:

- minificazione di HTML e CSS tramite plugin
- Maggiore facilità ad aggiungere e modificare pagine tramite markdown
- Semplicità nell'impostare permalink, gestione metadata e SEO
- Maggiore semplicità e versatilità in caso venisse deciso, in futuro, di implementare un piccolo blog contentente istruzioni per i volontari, oppure molto più semplicemente per sfruttare Liquid e i `for` loop

Forse la questione è già stata discussa, ma credo sia una discussione che sarebbe interessante avere.

**Comment by Sav22999** [comment]
Per le voci in generale potrebbe essere una buona soluzione, anche se attualmente credo si stia procedendo assolutamente bene.

Il blog, ti dico già da ora, non sarà riproposto in futuro. Il sito sarà statico il più possibile.

Puoi leggere le differenze tra sito nuovo e sito vecchio sul README (quando hai aperto lo issue ancora non lo avevo scritto, scusami)

**Comment by Sav22999** [comment]
Come discusso nel gruppo Design, non serve utilizzare Jekyll o altro.
In primis per non avere una dipendenza (poiché sviluppiamo in HTML puro), poi perché il sito è estremamente minimale e totalmente statico e non ha senso utilizzarli.
