### ISSUE TITLE
Creare pagina "FAQ"

### ISSUE THREAD

**Issue by xplosionmind** [MozillaItalia/mozillaitalia.github.io#38]
La pagina "FAQ" è presente nella sezione "Link utili" dell'index, ma non è ancora stata creata. Sarebbe forse utile inserire qui alcune domande a cui rispondere.

**Comment by dag7dev** [comment]
Per avere la pagina FAQ dovremmo stilare una lista delle FAQ e relative risposte. Vuoi occupartene tu?

**Comment by Sav22999** [comment]
@xplosionmind Hai assolutamente ragione. Il problema, però, non sono tanto le domande/risposte quanto la grafica.
Come testo "sample" usa "Lorem Ipsum" ;)

**Comment by dag7dev** [comment]
@Sav22999 sono anche un problema in realtà i testi, bisogna averceli prima di tutto!

**Comment by Sav22999** [comment]
Sì, ma per velocizzare il tutto si può utilizzare Lorem Ipsum per ora. Anche perché, **ricordo**, tutto il sito deve essere prima sottoposto a revisione ;)

**Comment by dag7dev** [comment]
@Sav22999 sì e siamo d'accordo come placeholder, però è sempre meglio buttare giù qualcosa, altrimenti non lo finiremo mai

EDIT: intendo che bisogna inventarsi qualcosa, altrimenti non la si mette ecco
