### ISSUE TITLE
Convertire il logo principale in SVG

### ISSUE THREAD

**Issue by xplosionmind** [MozillaItalia/mozillaitalia.github.io#40]
Il logo in cima in `index.html` è un png di larghezza 283px. Secondo me sarebbe il caso di sostituirlo con un SVG, in modo che non appaia sgranato sui display a risoluzione più alta e che magari possa anche essere ingrandito un po'.

**Comment by Sav22999** [comment]
@xplosionmind c'è già la SVG pronta. Il problema era che le SVG non leggono bene i font e non veniva bene la scritta "mozilla" "Italia"

**Comment by xplosionmind** [comment]
Aah, ho capito. Ho avuto questo problema anche io. Bisogna convertire il font in oggetto, in modo che se il font specifico non è installato, o se ci fosse qualche problema, "Mozilla Italia" si vede correttamente.

**Comment by Sav22999** [comment]
Certo, puoi provare. Trovi tutto nel repo "Assets" di Mozilla Italia ;)

**Comment by Sav22999** [comment]
Chiudo questo issue, poiché è stato stabilito che il logo esiste già come SVG
