### ISSUE TITLE
Trasferire documentazione l10n su sito principale

### ISSUE THREAD

**Issue by xplosionmind** [MozillaItalia/mozillaitalia.github.io#43]
Avevamo già discusso, in una riunione, di accorpare tutte le risorse, le linee guida e i link presenti su <https://mozillaitalia.gitbooks.io/l10n-guide/content/>. Secondo me, sarebbe molto utile per diversi motivi, principalmente:
- in un solo link (che sarà quello di mozillaitalia.org) si possono trovare tutte le informazioni necessarie, senza doversi necessariamente spostare su GitHub per capire come tradurre leggendo in diversi luoghi
- non sarebbe più necesario aprire ogni issue di traduzione copiando e incollando la lista lunghissima di link utili, dato che il contenuto può essere spostato in una pagina dedicata del sito, per esempio chiamata "Vademecum di taduzione articolo"

Cosa ne dite @kitsunenosaraT e @Sav22999?

Questo pensiero mi è sorto dopo aver cominciato a strutturare la pagina del sito dedicata alla localizzazione, come da #24.

**Comment by Sav22999** [comment]
Come ho scritto su #24, la documentazione è necessaria, oltre ad essere ben scritta, completa e utile.
Piuttosto, inserire nella pagina dei punti salienti (ad esempio il "processo di traduzione" e le sua fasi), alcuni strumenti utili da utilizzare (Pontoon, MozIta L10n Addon, Transvision, eccetera)

**Comment by kitsunenosaraT** [comment]
@xplosionmind 
 
> in un solo link (che sarà quello di mozillaitalia.org) si possono trovare tutte le informazioni necessarie, senza doversi necessariamente spostare su GitHub per capire come tradurre leggendo in diversi luoghi

Mi sembra un'ottima iniziativa che la guida e più dettagli sul lavoro del team di localizzazione compaiano *anche* su MozillaItalia.org per i potenziali collaboratori che non hanno dimestichezza con GitHub.

Fermo restando questo, purtroppo GitHub continua a servirci per gestire gli issue settimanali e anche per dare la possibilità a tutti di contribuire alla guida tramite il meccanismo delle pull request.
Quindi alla fine si tratterebbe di una copia di cortesia, mentre il cuore dell'azione rimarrebbe su GitHub.

> non sarebbe più necesario aprire ogni issue di traduzione copiando e incollando la lista lunghissima di link utili, dato che il contenuto può essere spostato in una pagina dedicata del sito, per esempio chiamata "Vademecum di taduzione articolo"

Questa proposta di non includere la sezione "Link utili" e altre informazioni nello issue settimanale è già stata fatta tanto tempo fa. Riporto le stesse risposte che detti allora:
1. [Guardandola](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/issues/266), non la definirei affatto una lista "lunghissima". Inoltre, essendo uno issue generato da template, non costa nessuna fatica copiarlo in ogni issue.
2. Tutte quelle informazioni fa comodo averle *a portata di mano mentre traduci*, proprio per questo le ho inserite nello issue settimanale, che tutti i volontari devono aprire per prenotarsi/chiedere il QA. Già in molti non leggono neanche le prime righe del messaggio di apertura dello issue dove si spiegano i vari passaggi della traduzione, se dovessero aprire un'ulteriore link solo per controllare una fonte o un sito di test, chi ci guarderebbe più?

Onestamente, non capisco ancora che fastidio può dare avere tutte le informazioni nello issue. Non devi leggerle per forza, ma quando ti servono ce le hai lì, a portata di mano, sulla pagina che tanto hai già aperta.

A questo punto vorrei sentire cosa ne pensa *chi è attivamente coinvolto nella traduzione*, cioè chi quei link li deve usare.
Se agli altri traduttori avere tutte le informazioni nello issue settimanale crea problemi, allora togliamoli pure.

**Comment by danielebarell** [comment]
@xplosionmind 
Ciao Tommi, 
Sara e Saverio
spero tutto ok.

Io mi trovo piuttosto bene nella situazione attuale.
Le info di base ripetute in ogni issue a me non danno fastidio e penso che per chi inizia o chi si attiva una-tantum sia molto comodo averle belle pronte.

> Mi sembra un'ottima iniziativa che la guida e più dettagli sul lavoro del team di localizzazione compaiano anche su MozillaItalia.org per i potenziali collaboratori che non hanno dimestichezza con GitHub.

Esattamente.
La cosa fondamentale secondo me è che le informazioni ovunque vengano pubblicate siano consistenti, cioè che **non si contraddicano l'una con l'altra**, quindi va benissimo metterle sul mozilla.org, in YouTube, in un repo gitHub, fare slide di presentazione etc. L'importante è conservare una mappa per cui, quando qualcosa cambia, si sa bene dove intervenire, cosa aggiornare e cosa rimuovere.

Buona serata
:)

**Comment by Sav22999** [comment]
L'idea è proprio questa: avere tutti i link a portata di click (sia essa la documentazione, strumenti utilizzati, e quant'altro).
Un po' come è, attualmente, la scaletta dello issue settimanale.

Per la rimozione della scaletta, ne avevamo parlato proprio in un meeting (lo proposi io) e c'erano pareri contrastanti, tra chi la voleva e chi meno. Dal momento che è sempre meglio specificare, piuttosto che rimuovere, si è deciso di lasciarla.

**Comment by xplosionmind** [comment]
Grazie a tutti. Dunque, io ho fatto questa proposta con l'idea di riuscire ad unire definitivamente anche nel futuro tutto in uno stesso luogo.

Riguardo quello che scrive @kitsunenosaraT:

> Questa proposta di non includere la sezione "Link utili" e altre informazioni nello issue settimanale è già stata fatta tanto tempo fa. Riporto le stesse risposte che detti allora:
> 
> 1. [Guardandola](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/issues/266), non la definirei affatto una lista "lunghissima". Inoltre, essendo uno issue generato da template, non costa nessuna fatica copiarlo in ogni issue.
> 
> 2. Tutte quelle informazioni fa comodo averle _a portata di mano mentre traduci_, proprio per questo le ho inserite nello issue settimanale, che tutti i volontari devono aprire per prenotarsi/chiedere il QA. Già in molti non leggono neanche le prime righe del messaggio di apertura dello issue dove si spiegano i vari passaggi della traduzione, se dovessero aprire un'ulteriore link solo per controllare una fonte o un sito di test, chi ci guarderebbe più?

Capisco, ricordavo le discussioni ma non le conclusioni che erano state raggiunte. In realtà, io ho confuso in uno stesso issue e nella stessa discussione due proposte differenti:
1. Spostare tutti i link presenti nell'issue di template per le traduzioni in una pagina di riferimento;
2. Spostare la documentazione da GitBooks sul sito principale.

Per il primo punto, direi che, rispettando quanto indicato da @Sav22999 e @danielebarell, non è utile cambiare questo workflow. Ho avanzato questa idea perché per quanto mi riguarda tenere durante una traduzione una pagina del sito con tutto quello che mi serve è più comodo che tenere un issue, ma probabilmente è soggettivo.

Riguardo al secondo punto, invece, vorrei specificare che io non parlavo di *rimuovere* o cambiare il sistema con cui è organizzata la documentazione l10n, ho pensato che sarebbe molto più semplice e comodo avere la documentazione hostata su `mozillaitalia.org/documentazione-l10n`, per esempio.

Dato che nell'issue #35 ho proposto di utilizzare Jekyll, potrebbe essere interessante soprattutto per la gestione dei contenuti e per uniformarli alla struttura di tutto il sito (anche stilisticamente).

Per quanto riguarda la pagina di *presentazione* di l10n, fare riferimento a #24.

**Comment by danielebarell** [comment]
> Ho avanzato questa idea perché per quanto mi riguarda tenere durante una traduzione una pagina del sito con tutto quello che mi serve è più comodo che tenere un issue, 

Ciao,
Al momento per approcciare la traduzione faccio così:
- Tengo due finestre del browser aperte separatamente;
- In una le schede riguardanti l'articolo specifico (quindi la l'issue, la pagina con l'articolo da tradurre, gli articoli correlati, ecc);
- Nell'altra le schede con gli strumenti on-line (traduttore generico, traduttore di termini tecnici specifici, dizionario italiano, ecc);

Tenere i riferimenti statici, cioé la guida e gli strumenti per tradurre che utilizziamo sempre e comunque in una singola pagina web trovo che possa essere ragionevole; tuttavia credo che si debba sopratutto pensare di facilitare la vita a chi traduce per la prima volta o saltuariamente, destinando questa persona in un luogo (l'issue) dove ha tutte indicazioni operative e strumentali chiare e subito disponibili, pazienza se sono un po' lunghe e ripetitive.

**Comment by dag7dev** [comment]
@xplosionmind secondo me invece dovremmo lasciare tutto su gitbooks. è più elegante, sebbene richieda più click e ho capito che intendi, sebbene sia favorevole per l'accorpamento, questa volta devo dirti che preferisco la soluzione gitbooks.

**Comment by Sav22999** [comment]
In quanto la decisione di lasciare tutto su gitbooks era già stata discussa in un meeting mensile, chiudo questo issue (anche perché c'è lo issue dedicato alla pagina localizzazione #24 )
