### ISSUE TITLE
Fixare i loghi

### ISSUE THREAD

**Issue by dag7dev** [MozillaItalia/mozillaitalia.github.io#45]
Non so se questo problema è presente anche nei gruppi telegram:
![](https://i.imgur.com/0YXwDRM.png)

**Comment by Sav22999** [comment]
Qual è il problema? Non vedo descrizione del problema 🤔

**Comment by dag7dev** [comment]
Non so se si vede dallo screenshot: le icone cerchiate in verde hanno un bordo sulla sinistra sottilissimo che non è in linea con tutte le altre icone (vai a vedere per esempio home e guarda quanto è distanziato dal bordo esterno).

Tutte le icone dovrebbero avere quel bordo (come home news e gli altri)

**Comment by Sav22999** [comment]
L'icona è quadrata. È ovvio che "Developer" sia più lungo di "L10n". Di conseguenza lo spazio è minore, poiché sono centrate

**Comment by dag7dev** [comment]
Forse basta renderle tutte trasparenti e problema risolto...

**Comment by Sav22999** [comment]
Sì, era già in previsione, ma a quanto apre ne avevo discusso in un altra chat e mai aperto un issue. Ho aperto il #51

**Comment by Sav22999** [comment]
Problema trasferito allo issue #51
