### ISSUE TITLE
Aggiungere GitHub nel footer

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/mozillaitalia.github.io#49]
Aggiungere l'organizzazione "Mozilla Italia" su GitHub nel footer

**Comment by dag7dev** [comment]
Tocca fare pure l'icona allora...

**Comment by Sav22999** [comment]
Credo ci sia già nel font utilizzato per twitter, facebook, ecc.

**Comment by dag7dev** [comment]
Credi bene. Aggiorno così chiudiamo!
