### ISSUE TITLE
Aggiungere dark mode

### ISSUE THREAD

**Issue by dag7dev** [MozillaItalia/mozillaitalia.github.io#50]
Aggiungere un pulsante che cliccandolo inverte tutti i colori del sito o rende i colori compatibili. Attualmente non è compatibile nemmeno con l'estensione Dark Reader, e questo è un problema non di poco conto

**Comment by Sav22999** [comment]
Con Dark Reader è ora fruibile. Per evitare di complicare (e appesantire) il codice per una funzionalità che, probabilmente, pochi utilizzerebbero chiudo questo issue (utilizzo il principio informatico del KISS). Eventualmente, se dovesse essere necessario, lo si riapre in futuro.
