### ISSUE TITLE
Revisionare contenuti del sito web

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/mozillaitalia.github.io#66]
- [x] Home page https://mozillaitalia.github.io/
- [x] L10n https://mozillaitalia.github.io/l10n/
- [x] Utilizzo logo https://mozillaitalia.github.io/utilizzo-logo
- [x] Contatti https://mozillaitalia.github.io/contatti
- [x] FAQ https://mozillaitalia.github.io/faq
- [x] Download https://mozillaitalia.github.io/download

**Comment by gioxx** [comment]
Issue #76, manca solo l10n ma provvedo al volo.

**Comment by gioxx** [comment]
Andata anche la pagina di l10n: https://github.com/MozillaItalia/mozillaitalia.github.io/commit/8a95b0d9f368ff1a11d02aa611a1fe6322db369e
