### ISSUE TITLE
Gestire Error 404 (ecc.)

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/mozillaitalia.github.io#67]

**Comment by Mte90** [comment]
Se rimaniamo su Github non possiamo fare niente, se lo spostiamo su un altro web server ci sono altre possibilità di usare dei file statici per le varie pagine.

**Comment by Sav22999** [comment]
Ma non lo dobbiamo, successivamente, hostare sull'hosting di mozillaitalia attuale?

**Comment by Sav22999** [comment]
Da Internet ho trovato questo commit, che funziona correttamente. Si può adottare la stessa soluzione https://github.com/lionello/lionello.github.io/commit/c175f6524a53e29aea1890c8a758afd0e8944852

**Comment by Mte90** [comment]
> Ma non lo dobbiamo, successivamente, hostare sull'hosting di mozillaitalia attuale?

Finchè il sito non è finito non posso ne confermare o negare XD
