### ISSUE TITLE
Rimuovere MDN dalla pagina dedicata alla localizzazione

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/mozillaitalia.github.io#75]
Il progetto MDN è stato ufficialmente inserito in modalità "Read-only" per la lingua italiana, quindi bisogna rimuovere questo progetto

**Comment by gioxx** [comment]
Rimosso nel commit https://github.com/MozillaItalia/mozillaitalia.github.io/commit/8a95b0d9f368ff1a11d02aa611a1fe6322db369e
