### ISSUE TITLE
Header e footer "parziali"

### ISSUE THREAD

**Issue by dag7dev** [MozillaItalia/mozillaitalia.github.io#84]
Non so se qualcuno lo sapeva, ma con Jekyll (o altri framework) c'è la possibilità di inserire header parziali, ossia dei "pezzi" di HTML da includere in altre pagine. Gli header e i footer si prestano molto bene a quanto sto cercando di spiegare, perchè appunto sono "pezzi statici" che devono comparire in tutte le pagine.
Quindi una specifica pagina senza parziale risulterà pressapoco così (com'è ora):
```
<html>

<head>
</head>

<body>
<div class = "header">
blablabla
</div>
---
</body>

</html>
```

CON il parziale risulterà pressapoco così:
```
<html>
<body>
{{template_header.html}}
roba
</body>
</html>
```

Potete vederlo come un "include" del PHP per chi mastica PHP.

Noi attualmente non abbiamo problemi a cambiare gli header di tanto in tanto, il problema però si viene a creare quando bisogna cambiare i contenuti nell'header e nel footer: bisogna farlo per ogni pagina.

Propongo allora, siccome il sito è stato rifatto da poco (e non credo che qualcuno vorrà rifarlo un'altra volta nel giro di pochi mesi utilizzando un altro framework "solo perché ha questa cosa degli header parziali") di fare uno scriptino in JS con delle funzioncine che creino header e footer.

In questo modo basterà toccare un solo file affinché si cambino header e footer in maniera più agevole.

**Comment by Mte90** [comment]
Jekyll è un generatore di siti statici, si può fare anche questo via CI che generi poi nel repo il tutto già compilato.

Vedete voi, una volta che è stato finito (i vari ticket minori) si può anche considerare su un ramo.

**Comment by Sav22999** [comment]
L'idea di questo sito era renderlo il più statico possibile, altrimenti, banalmente senza usare framework esterni, lo si può fare mediante JavaScript Vanilla.

Rimango dell'opinione di lasciarlo così com'è, personalmente.
