### ISSUE TITLE
Aggiungere CV Project?

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/mozillaitalia.github.io#96]
Qui chiedo a voi, perché io non sono super partes. Mozilla ha finanziato, quindi "accettato" effettivamente il progetto, e molti utenti la tutt'ora per [contribuire](https://www.saveriomorelli.com/commonvoice/app-usage/).

Propongo: se si visualizza il sito da mobile-Android, di mostrare un messaggio in alto simile a "Sai che puoi contribuire a Common Voice dal tuo telefono Android? Usa CV Project ora!" O qualcosa del genere.

Ditemi voi

**Comment by Mte90** [comment]
un avviso da mobile ci sta assolutamente
